### ISSUE TITLE
Problema com instalação de modulo "Plano de Contas Simplificado Brasil"

### ISSUE THREAD

**Issue by ahmedgenina** [Trust-Code/Tutorial-Instalacao#5]
Ola equipe da Trustcode , muito obrigado pelo tutorial ,  ao instalar o modulo "Plano de Contas Simplificado Brasil" deu o erro abaixo 

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1129, in run
    result = request.env['ir.actions.server'].browse([action_id]).run()
  File "/opt/odoo/odoo/addons/base/ir/ir_actions.py", line 972, in run
    res = func(action, eval_context=eval_context)
  File "/opt/odoo/addons/website/models/ir_actions.py", line 58, in run_action_code_multi
    res = super(ServerAction, self).run_action_code_multi(action, eval_context)
  File "/opt/odoo/odoo/addons/base/ir/ir_actions.py", line 795, in run_action_code_multi
    safe_eval(action.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/opt/odoo/odoo/tools/safe_eval.py", line 301, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/tools/convert.py", line 710, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo/addons/base/ir/ir_model.py", line 1192, in _update
    record = record.create(values)
  File "/opt/odoo/odoo/models.py", line 3810, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo/models.py", line 3900, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/opt/odoo/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ValueError: <class 'odoo.tools.convert.ParseError'>: "" while evaluating
u'records.button_immediate_install()'

**OBS**  todos os outros módulos da localização foram instalados com sucesso.

Alguém pode me ajudar a resolver isso , pois a mensagem de erro não esta clara pra mim 

Grato

**Comment by danimaribeiro** [comment]
Tente com uma nova base de dados.
Certifique-se que os branchs estão todos na 10.0

**Comment by fbsdev** [comment]
Boa tarde, também queria instalar um plano de contas, mas ocorreu o mesmo erro, testei com uma nova maquina Ubuntu, nova base de dados, tudo atualizado.

**Comment by danimaribeiro** [comment]
Alguém consegue gravar um video sobre o erro?
